### ISSUE TITLE
build task does almost nothing

### ISSUE THREAD

**Issue by violacase** [Sebastian-Fitzner/Veams#4] opened 2016-04-01 07:29 UTC
Hi there,
After succesfully installing everything on:

Windows 10
node v4.4.1
npm 3.8.3

and creating a new project `npm install` gives:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN veams@0.0.1 No repository field.
npm WARN veams@0.0.1 No license field.
```

Since it are just warnings (I hoped) I continued with `npm start`.

Without any warnings the build process finished and served. `Gulp serve` pops up my browser with only `Cannot GET /`

Examining the build I noticed almost no files had been generated.

Any idea what is happening here?

**Comment by Sebastian-Fitzner** [comment] 2016-05-13 05:09
Hi,

sorry for the late response but I was in parental leave for over a month. Now I am back in town ;). 

The problem is that we hadn't integrated a template engine in Gulp, see:

https://github.com/Sebastian-Fitzner/generator-veams/issues/60

But til next week this is solved, because now I have written a powerful template engine by myself which can be used in Grunt and Gulp.

I will close this ticket, when [Mangony](https://github.com/Sebastian-Fitzner/mangony) is integrated.

**Comment by Sebastian-Fitzner** [comment] 2016-05-26 07:19
WIth the latest version, Veams supports Mangony and Gulp - have fun.

**Closed by Sebastian-Fitzner** 2016-05-26 07:19 UTC
